export const ADD_ITEM = 'ADD_ITEM'

export const EDIT_ITEM = 'EDIT_ITEM'

export const EDIT_ARRAY_ITEM = 'EDIT_ARRAY_ITEM'

export const REMOVE_ARRAY_ITEM = 'REMOVE_ARRAY_ITEM'

export const ADD_MODULE = 'ADD_MODULE'

export const ADD_CUSTOMIZED_MODULE = 'ADD_CUSTOMIZED_MODULE'

export const EDIT_CUSTOMIZED_NAME = 'EDIT_CUSTOMIZED_NAME'

export const ADD_CUSTOMIZED_ITEM = 'ADD_CUSTOMIZED_ITEM'

export const SET_JOB_TITLE_TREE = 'SET_JOB_TITLE_TREE'
